# This is a basic workflow that is manually triggered

name: local branch testing workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branchName:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to run:'
        # Default value if no value is explicitly provided
        default: 'master'
        # Input has to be provided for the workflow to run
        required: false

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_build_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch to run: ${{ github.event.inputs.branchName }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branchName }}
          persist-credentials: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: sed pom.xml
        run: sed -i '/^  <\/modules>/i \    <module>activemq-unit-tests<\/module>\n    <module>activemq-karaf-itest<\/module> \n    <module>activemq-itests-spring31<\/module>' pom.xml
      - name: Build with Maven
        run: mvn -U -B -e clean install -DskipTests

      - name: unit test run
        run: |
          cd activemq-unit-tests
          mvn -B -e test
